### ISSUE TITLE
Merge interesting forks

### ISSUE THREAD

**Issue by philipmat** [philipmat/discogs-xml2db#17] opened 2014-03-27 15:42 UTC
There is some interesting work done on some forks. Merge them back:
- [ ] https://github.com/Jokipii/discogs-xml2db
- [ ] https://github.com/bmcfee/discogs-import
- [ ] https://github.com/crossjam/discogs-import
- [ ] https://github.com/kaikasurinen/discogs-import
- [ ] https://github.com/echonest/discogs-import
- [ ] https://github.com/buremba/discogs-import
- [ ] https://github.com/mariozig/discogs-import

**Comment by pfouque** [comment] 2017-02-10 12:56
Lot of them have been removed and replaced by your repository, among the others only 2 remain interesting: 
- https://github.com/Jokipii/discogs-xml2db: this one is focused on speedup the process
- https://github.com/bmcfee/discogs-import: this one is mostly file organization to turn it into a python module.

If you want i can merge the last one. Are you still interested ?

**Comment by philipmat** [comment] 2017-02-10 15:24
Pascal, I certainly am interested, but I have a few concerns.

## bmcfee fork

My main concern with this is around how successful the merge will be given that not only does it reorganize the files but it also applies various patches - and it has done all that on a version that's not quite up-to-date. Furthermore, due to the modularization, a good deal of the commands described in the README are now no longer valid.

So it's not a straight merge, further corrections need to be applied.

If I had time, I'd use the lessons of that fork and properly turn it into a module. Although.... now that I think about it, to be perfectly honest I'm not really sure what the benefit would be. I can't see anybody importing this module to be used in other code.

## Jokipii fork

Seems to have some large change-set under the deceptive comment of "simple changes". Take a look at the diffs of [564d679a862](https://github.com/Jokipii/discogs-xml2db/commit/564d679a862cb24e3c751fbb41e79d732c7e94ee). Perhaps it's just line-end changes, perhaps it's just re-indentation, but either way it pollutes the history quite significantly.

There's also [database structure changes](https://github.com/Jokipii/discogs-xml2db/commit/2733e7c4f0b9c59c2273027705224d11f672e07f), of which I understand the reasoning behind some but not all, and that's something I'm a lot more hesitant to roll with.

If I had the time, I'd go through each of the changes and cherry-pick those that are appropriate, but I'm also concerned with how much that branch has actually been tested and what speedup improvements are we actually seeing.

**Comment by pfouque** [comment] 2017-02-13 10:02
Hi,

I have not inspected jokipii fork, i listed it because it is still alive and i know there are some concerns around about performance and desire to speed up the process. I agree with you, this fork needs time (and testing) to measure benefits and pitfalls.

I also faced the problem of comparing codes with tabs and spaces indentation, according to PEP8 "spaces are the preferred indentation method". But even if you can replace tabs with spaces you will have the same problem comparing fork which use tabs to indent. Fortunately there is no file mixing both, but some files are indented using tabs and others using spaces. 
So even if I prefer spaces, this choice is up to you.

The most interesting point in bmcfee fork is modularization, this fork contains only file re organization, but by pushing it one step further we can give ability to users to import and override some parts of the code. it's also a good start to tackle duplicated code.

Applied patches is not a problem, they are already applied by someone else on your repository.

So perhaps we can just keep file organization but keeping external interface to be compliant with commands described in README.

If you want i can prepare a PR, as the work is almost done.

**Comment by philipmat** [comment] 2017-02-13 13:05
I will definitely accept a PR; all I'm asking is that you spend some time testing it (maybe do a full import?).

**Comment by ijabz** [comment] 2017-02-13 13:30
I would be against merging Jokipiis fork it three years old, changes have been made since then I really don't think it adds anything. Multithreading to speed up plsql import is the wrong approach, the problem is that sql is inserting records one at a time into database instead just writing them to a file and using dbcopy at the end. For comparison mbslave project for importing musicbrainz data into a postgres database only takes me about 10 minutes. I would like to rewrite the code to do what ive said but as I don't know python that is a bit of a task for me but maybe you could do it, just replace sql insert statements with writing to files, each files representing a different database table then do dbcopy at the end.

**Comment by philipmat** [comment] 2017-02-13 14:17
@ijabz - this is what #35 is about. I've made a little bit of progress on it, but then I ran into the issue that it's not just xml-straight-to-inserts, the current code actually relies on looking up previously inserted things in order to fulfill FK requirements. That would keep up from a flat file, unless we redo the PKs and FKs to be GUIDs.

**Comment by pfouque** [comment] 2017-02-14 08:35
Fortunately, i'm doing a full import almost every month.

**Comment by ijabz** [comment] 2017-02-20 11:54
Regarding #35 more info on specific problem you encountered would be useful. But in general I think you could solve this by importing into denormalized tables, and then use SQL to insert into the final tables form the denormalized tables. That would still be an order of magnitude quicker than the current approach of inserting one record at a time

**Comment by ijabz** [comment] 2020-07-29 09:47
This has now been superceded, closing.

**Closed by ijabz** 2020-07-29 09:47 UTC
