### ISSUE TITLE
Error when importing discogs data into PostgreSQL

### ISSUE THREAD

**Issue by PattMayne** [philipmat/discogs-xml2db#58] opened 2015-05-08 03:06 UTC
The process crashed when it hit the "masters" section. Here's the output:

  File "discogsparser.py", line 241, in <module>
    main(sys.argv[1:])
  File "discogsparser.py", line 236, in main
    parseMasters(parser, exporter)
  File "discogsparser.py", line 171, in parseMasters
    parser.parse(master_file)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 307, in end_element
    self._cont_handler.endElement(name)
  File "/home/thephltr/webapps/who_pro/discogs_importer/discogsmasterparser.py", line 173, in endElement
    self.exporter.storeMaster(self.master)
  File "/home/thephltr/webapps/who_pro/discogs_importer/postgresexporter.py", line 323, in storeMaster
    (img.uri, img.image_type, master.id))
AttributeError: ImageInfo instance has no attribute 'image_type'

**Comment by ijabz** [comment] 2015-05-13 09:05
Duplicate of #52

**Closed by ijabz** 2015-05-13 09:05 UTC
